# Generated by Django 3.2.18 on 2023-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0008_alter_asnlistmodel_transportation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asnlistmodel',
            name='transportation_fee',
            field=models.CharField(max_length=255, verbose_name='Transportation Fee'),
        ),
    ]
